[workspace]
members = [
  "api",
  "cargo-shuttle",
  "codegen",
  "common",
  "proto",
  "provisioner",
  "service"
]
exclude = [
  "e2e",
  "cargo-0.63.1",
  "examples"
]

#[patch.crates-io]
#cargo = { path = "./cargo-0.63.1" }
