[workspace]
members = [
  "api",
  "cargo-shuttle",
  "codegen",
  "common",
  "proto",
  "provisioner",
  "service"
]
exclude = [
  "e2e",
  "examples"
]

[patch.crates-io]
cargo = { git = "https://github.com/SonicZentropy/cargo.git" }
