[package]
name = "hello-world-panic"
version = "0.1.0"
edition = "2021"
description = "a rocket example that intentionally panics while loading"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
shuttle-service = "0.2.1"
